name: StaffBypass
version: 1.0
main: fr.hamta.StaffBypass
api-version: 1.20
author: Hamta
description: Permet aux staffs avec une permission spéciale de bypass la limite du serveur.

permissions:
  staffbypass.joinfull:
    description: Permet de bypass la limite du serveur.
    default: op
