name: StaffBypass
version: 1.1
main: fr.hamta.StaffBypass
api-version: 1.20
author: Hamta
description: Permet à certains joueurs définis par UUID de bypass la limite du serveur.

commands:
  staffbypass:
    description: Gestion du plugin StaffBypass
    usage: /staffbypass <add|reload>
    permission: op
